name: Publish to Winget
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g. 1.2.9)'
        required: true
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Version
        id: get_version
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            VERSION=${{ github.event.release.tag_name }}
            echo "version=${VERSION#v}" >> $GITHUB_OUTPUT
          fi
      - name: Publish to Winget
        uses: microsoft/winget-create-action@v2
        with:
          version: ${{ steps.get_version.outputs.version }}
          installer-url: https://github.com/duyxyz/GIF-Overlay/releases/download/v${{ steps.get_version.outputs.version }}/GIF-Overlay-Setup.exe
          token: ${{ secrets.WINGET_TOKEN }}
